"use client";

import { useState } from "react";
import { generatePlainLanguageCopyAction } from "@/lib/actions";
import type { CaseRecord } from "@/lib/types";

export function PlainLanguageCopy({
  caseId,
  language,
  existing,
  hasQuestions,
}: {
  caseId: string;
  language: string;
  existing: CaseRecord["plainLanguageCopy"];
  hasQuestions: boolean;
}) {
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  return (
    <div className="border p-5" style={{ borderColor: "var(--rule-strong)" }}>
      <div className="flex items-center justify-between flex-wrap gap-3 mb-3">
        <p style={{ color: "var(--ink-soft)" }}>
          A translated, plain-language copy of this application in {language || "the applicant’s language"}, for the
          citizen. Machine-generated, always shown beside the formal filing, and reviewed before it is handed over.
        </p>
        <button
          type="button"
          disabled={pending || !hasQuestions}
          onClick={async () => {
            setPending(true);
            setError(null);
            const result = await generatePlainLanguageCopyAction(caseId);
            if (!result.ok) setError(result.error);
            setPending(false);
          }}
          className="border-2 px-4 py-2 text-sm font-semibold shrink-0 disabled:opacity-40"
          style={{ borderColor: "var(--ink)", color: "var(--ink)" }}
        >
          {pending ? "Generating…" : existing ? "Regenerate" : "Generate with Gemini"}
        </button>
      </div>

      {!hasQuestions && (
        <p className="text-sm" style={{ color: "var(--ink-faint)" }}>
          Add at least one question before generating a plain-language copy.
        </p>
      )}

      {error && (
        <p className="text-sm border p-3" style={{ borderColor: "var(--brick)", color: "var(--brick)" }}>
          {error}
        </p>
      )}

      {existing && (
        <div className="mt-3 border p-4 text-sm whitespace-pre-wrap" style={{ borderColor: "var(--rule)", background: "var(--paper-raised)", color: "var(--ink)" }}>
          {existing.text}
          <p className="text-xs mt-3 pt-3 border-t not-italic" style={{ borderColor: "var(--rule)", color: "var(--ink-faint)" }}>
            Generated by {existing.model} on {new Date(existing.generatedAt).toLocaleString()}. Machine-translated;
            check it reads correctly before sharing it with the citizen.
          </p>
        </div>
      )}
    </div>
  );
}
